// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Req
	RespBody
	Resp
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/davidhenrygao/GolangTest/proto/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMD int32

const (
	CMD_LOGIN CMD = 1
)

var CMD_name = map[int32]string{
	1: "LOGIN",
}
var CMD_value = map[string]int32{
	"LOGIN": 1,
}

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}
func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}
func (x *CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_value, data, "CMD")
	if err != nil {
		return err
	}
	*x = CMD(value)
	return nil
}
func (CMD) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RetCode int32

const (
	RetCode_SUCCESS        RetCode = 0
	RetCode_PROTOCOL_ERROR RetCode = 1
	RetCode_WRONG_PASSWORD RetCode = 2
)

var RetCode_name = map[int32]string{
	0: "SUCCESS",
	1: "PROTOCOL_ERROR",
	2: "WRONG_PASSWORD",
}
var RetCode_value = map[string]int32{
	"SUCCESS":        0,
	"PROTOCOL_ERROR": 1,
	"WRONG_PASSWORD": 2,
}

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}
func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}
func (x *RetCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RetCode_value, data, "RetCode")
	if err != nil {
		return err
	}
	*x = RetCode(value)
	return nil
}
func (RetCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Req struct {
	Account          *string             `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string             `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Token            *string             `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	GameserverId     *int32              `protobuf:"varint,4,opt,name=gameserver_id" json:"gameserver_id,omitempty"`
	Msg              *string             `protobuf:"bytes,5,opt,name=msg" json:"msg,omitempty"`
	Infos            []*common.Extrainfo `protobuf:"bytes,6,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *Req) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Req) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Req) GetGameserverId() int32 {
	if m != nil && m.GameserverId != nil {
		return *m.GameserverId
	}
	return 0
}

func (m *Req) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *Req) GetInfos() []*common.Extrainfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type RespBody struct {
	Secrect          *string `protobuf:"bytes,1,opt,name=secrect" json:"secrect,omitempty"`
	MsgBack          *string `protobuf:"bytes,2,opt,name=msg_back" json:"msg_back,omitempty"`
	Options          []int32 `protobuf:"varint,3,rep,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RespBody) Reset()                    { *m = RespBody{} }
func (m *RespBody) String() string            { return proto.CompactTextString(m) }
func (*RespBody) ProtoMessage()               {}
func (*RespBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RespBody) GetSecrect() string {
	if m != nil && m.Secrect != nil {
		return *m.Secrect
	}
	return ""
}

func (m *RespBody) GetMsgBack() string {
	if m != nil && m.MsgBack != nil {
		return *m.MsgBack
	}
	return ""
}

func (m *RespBody) GetOptions() []int32 {
	if m != nil {
		return m.Options
	}
	return nil
}

type Resp struct {
	Rc               *int32              `protobuf:"varint,1,req,name=rc" json:"rc,omitempty"`
	RespBody         *RespBody           `protobuf:"bytes,2,opt,name=resp_body" json:"resp_body,omitempty"`
	Infos            []*common.Extrainfo `protobuf:"bytes,3,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Resp) Reset()                    { *m = Resp{} }
func (m *Resp) String() string            { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()               {}
func (*Resp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Resp) GetRc() int32 {
	if m != nil && m.Rc != nil {
		return *m.Rc
	}
	return 0
}

func (m *Resp) GetRespBody() *RespBody {
	if m != nil {
		return m.RespBody
	}
	return nil
}

func (m *Resp) GetInfos() []*common.Extrainfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*Req)(nil), "test.Req")
	proto.RegisterType((*RespBody)(nil), "test.RespBody")
	proto.RegisterType((*Resp)(nil), "test.Resp")
	proto.RegisterEnum("test.CMD", CMD_name, CMD_value)
	proto.RegisterEnum("test.RetCode", RetCode_name, RetCode_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd1, 0x41, 0xcb, 0xda, 0x30,
	0x1c, 0x06, 0xf0, 0xb5, 0xb1, 0xeb, 0xdb, 0x7f, 0x79, 0x5f, 0xbb, 0xc0, 0x20, 0xec, 0xd4, 0x79,
	0x2a, 0x1e, 0xda, 0xe1, 0x07, 0x10, 0x66, 0x15, 0x19, 0x38, 0x2b, 0xa9, 0x43, 0xd8, 0xa5, 0xc4,
	0x36, 0xab, 0xc5, 0xb5, 0xe9, 0x92, 0xe8, 0xe6, 0x61, 0xdf, 0x7d, 0xa4, 0x32, 0x6f, 0xef, 0x2d,
	0x3c, 0xe4, 0xe1, 0xf9, 0x91, 0x00, 0x68, 0xae, 0x74, 0xdc, 0x4b, 0xa1, 0x05, 0x1e, 0x99, 0xf3,
	0x87, 0x31, 0xff, 0xa3, 0x25, 0x6b, 0xba, 0x1f, 0xe2, 0x1e, 0x4f, 0xfe, 0x02, 0xa2, 0xfc, 0x17,
	0x1e, 0x83, 0xcb, 0xca, 0x52, 0x5c, 0x3a, 0x4d, 0xac, 0xd0, 0x8e, 0x3c, 0x1c, 0xc0, 0x53, 0xcf,
	0x94, 0xfa, 0x2d, 0x64, 0x45, 0xec, 0x21, 0x79, 0x06, 0x47, 0x8b, 0x33, 0xef, 0x08, 0x0a, 0xad,
	0xc8, 0xc3, 0xef, 0xe1, 0xb9, 0x66, 0x2d, 0x57, 0x5c, 0x5e, 0xb9, 0x2c, 0x9a, 0x8a, 0x8c, 0x42,
	0x2b, 0x72, 0xb0, 0x0f, 0xa8, 0x55, 0x35, 0x71, 0x86, 0x3b, 0x21, 0x38, 0x66, 0x4a, 0x91, 0xb7,
	0x21, 0x8a, 0xfc, 0xd9, 0xbb, 0xb8, 0x14, 0x6d, 0x2b, 0xba, 0x78, 0xf5, 0x1f, 0x31, 0x99, 0xc3,
	0x13, 0xe5, 0xaa, 0x5f, 0x88, 0xea, 0x66, 0x0c, 0x8a, 0x97, 0x92, 0x97, 0xc6, 0x60, 0xdd, 0x0d,
	0xad, 0xaa, 0x8b, 0x23, 0x2b, 0xcf, 0xc4, 0x1e, 0x92, 0x31, 0xb8, 0xa2, 0xd7, 0x8d, 0xe8, 0x14,
	0x41, 0x21, 0x8a, 0x9c, 0xc9, 0x01, 0x46, 0xa6, 0x8f, 0x01, 0x6c, 0x59, 0x0e, 0x74, 0x07, 0x7f,
	0x04, 0x4f, 0x72, 0xd5, 0x17, 0x47, 0x51, 0xdd, 0x86, 0x9e, 0x3f, 0x7b, 0x89, 0x87, 0x97, 0x78,
	0x4c, 0x3d, 0x60, 0xe8, 0x15, 0xd8, 0x34, 0x00, 0x94, 0x7e, 0x5d, 0x62, 0x0f, 0x9c, 0x4d, 0xb6,
	0xfe, 0xb2, 0x0d, 0xac, 0xe9, 0x1c, 0x5c, 0xca, 0x75, 0x2a, 0x2a, 0x8e, 0x7d, 0x70, 0xf3, 0x6f,
	0x69, 0xba, 0xca, 0xf3, 0xe0, 0x0d, 0xc6, 0xf0, 0xb2, 0xa3, 0xd9, 0x3e, 0x4b, 0xb3, 0x4d, 0xb1,
	0xa2, 0x34, 0xa3, 0x81, 0x65, 0xb2, 0x03, 0xcd, 0xb6, 0xeb, 0x62, 0xf7, 0x39, 0xcf, 0x0f, 0x19,
	0x5d, 0x06, 0xf6, 0xe2, 0xd3, 0xf7, 0xb8, 0x6e, 0xf4, 0xe9, 0x72, 0x34, 0x63, 0x49, 0xc5, 0xae,
	0x4d, 0x75, 0xe2, 0x9d, 0xbc, 0xd5, 0x4c, 0x24, 0x6b, 0xf1, 0x93, 0x75, 0xf5, 0x9e, 0x2b, 0x9d,
	0x0c, 0xdf, 0x92, 0x18, 0xee, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0xa0, 0x5f, 0x2a, 0xbf,
	0x01, 0x00, 0x00,
}
