// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CMD int32

const (
	CMD_LOGIN CMD = 1
)

var CMD_name = map[int32]string{
	1: "LOGIN",
}
var CMD_value = map[string]int32{
	"LOGIN": 1,
}

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}
func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}
func (x *CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_value, data, "CMD")
	if err != nil {
		return err
	}
	*x = CMD(value)
	return nil
}
func (CMD) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type RetCode int32

const (
	RetCode_SUCCESS        RetCode = 0
	RetCode_PROTOCOL_ERROR RetCode = 1
	RetCode_WRONG_PASSWORD RetCode = 2
)

var RetCode_name = map[int32]string{
	0: "SUCCESS",
	1: "PROTOCOL_ERROR",
	2: "WRONG_PASSWORD",
}
var RetCode_value = map[string]int32{
	"SUCCESS":        0,
	"PROTOCOL_ERROR": 1,
	"WRONG_PASSWORD": 2,
}

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}
func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}
func (x *RetCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RetCode_value, data, "RetCode")
	if err != nil {
		return err
	}
	*x = RetCode(value)
	return nil
}
func (RetCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type Req struct {
	Account          *string      `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string      `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Token            *string      `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	GameserverId     *int32       `protobuf:"varint,4,opt,name=gameserver_id" json:"gameserver_id,omitempty"`
	Msg              *string      `protobuf:"bytes,5,opt,name=msg" json:"msg,omitempty"`
	Infos            []*Extrainfo `protobuf:"bytes,6,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Req) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *Req) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Req) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Req) GetGameserverId() int32 {
	if m != nil && m.GameserverId != nil {
		return *m.GameserverId
	}
	return 0
}

func (m *Req) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *Req) GetInfos() []*Extrainfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type RespBody struct {
	Secrect          *string `protobuf:"bytes,1,opt,name=secrect" json:"secrect,omitempty"`
	MsgBack          *string `protobuf:"bytes,2,opt,name=msg_back" json:"msg_back,omitempty"`
	Options          []int32 `protobuf:"varint,3,rep,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RespBody) Reset()                    { *m = RespBody{} }
func (m *RespBody) String() string            { return proto.CompactTextString(m) }
func (*RespBody) ProtoMessage()               {}
func (*RespBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RespBody) GetSecrect() string {
	if m != nil && m.Secrect != nil {
		return *m.Secrect
	}
	return ""
}

func (m *RespBody) GetMsgBack() string {
	if m != nil && m.MsgBack != nil {
		return *m.MsgBack
	}
	return ""
}

func (m *RespBody) GetOptions() []int32 {
	if m != nil {
		return m.Options
	}
	return nil
}

type Resp struct {
	Rc               *int32       `protobuf:"varint,1,req,name=rc" json:"rc,omitempty"`
	RespBody         *RespBody    `protobuf:"bytes,2,opt,name=resp_body" json:"resp_body,omitempty"`
	Infos            []*Extrainfo `protobuf:"bytes,3,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Resp) Reset()                    { *m = Resp{} }
func (m *Resp) String() string            { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()               {}
func (*Resp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Resp) GetRc() int32 {
	if m != nil && m.Rc != nil {
		return *m.Rc
	}
	return 0
}

func (m *Resp) GetRespBody() *RespBody {
	if m != nil {
		return m.RespBody
	}
	return nil
}

func (m *Resp) GetInfos() []*Extrainfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*Req)(nil), "test.Req")
	proto.RegisterType((*RespBody)(nil), "test.RespBody")
	proto.RegisterType((*Resp)(nil), "test.Resp")
	proto.RegisterEnum("test.CMD", CMD_name, CMD_value)
	proto.RegisterEnum("test.RetCode", RetCode_name, RetCode_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xce, 0x4f, 0x6b, 0xe2, 0x40,
	0x18, 0xc7, 0xf1, 0x4d, 0xc6, 0xd9, 0x98, 0x27, 0x68, 0xc2, 0xc0, 0xc2, 0xb0, 0x87, 0x25, 0xeb,
	0x29, 0x78, 0xf0, 0xe0, 0x0b, 0x10, 0xda, 0x28, 0x52, 0xb0, 0x8e, 0x4c, 0x2a, 0x1e, 0x43, 0x4c,
	0x9e, 0x8a, 0x88, 0x99, 0x74, 0x66, 0xfa, 0x47, 0xfa, 0xe6, 0x4b, 0x22, 0xf5, 0xd4, 0xdb, 0xf0,
	0x65, 0x1e, 0x7e, 0x1f, 0x00, 0x8b, 0xc6, 0x4e, 0x1a, 0xad, 0xac, 0x62, 0xbd, 0xf6, 0xfd, 0x37,
	0xc4, 0x0f, 0xab, 0x8b, 0x63, 0xfd, 0xac, 0xae, 0x79, 0xf4, 0x09, 0x44, 0xe2, 0x0b, 0x0b, 0xc1,
	0x2b, 0xca, 0x52, 0xbd, 0xd6, 0x96, 0x3b, 0xb1, 0x9b, 0xf8, 0x2c, 0x82, 0x7e, 0x53, 0x18, 0xf3,
	0xae, 0x74, 0xc5, 0xdd, 0xae, 0x0c, 0x80, 0x5a, 0x75, 0xc2, 0x9a, 0x93, 0xd8, 0x49, 0x7c, 0xf6,
	0x07, 0x06, 0x87, 0xe2, 0x8c, 0x06, 0xf5, 0x1b, 0xea, 0xfc, 0x58, 0xf1, 0x5e, 0xec, 0x24, 0x94,
	0x05, 0x40, 0xce, 0xe6, 0xc0, 0x69, 0xf7, 0xe7, 0x1f, 0xd0, 0x76, 0xca, 0xf0, 0xdf, 0x31, 0x49,
	0x82, 0x69, 0x38, 0xe9, 0x3c, 0x8b, 0x6f, 0xc2, 0x68, 0x06, 0x7d, 0x89, 0xa6, 0xb9, 0x57, 0xd5,
	0xa5, 0x15, 0x18, 0x2c, 0x35, 0x96, 0xad, 0xc0, 0xb9, 0x0a, 0xce, 0xe6, 0x90, 0xef, 0x8b, 0xf2,
	0xc4, 0xdd, 0xae, 0x84, 0xe0, 0xa9, 0xc6, 0x1e, 0x55, 0x6d, 0x38, 0x89, 0x49, 0x42, 0x47, 0x5b,
	0xe8, 0xb5, 0xf7, 0x0c, 0xc0, 0xd5, 0x65, 0x07, 0xa7, 0xec, 0x3f, 0xf8, 0x1a, 0x4d, 0x93, 0xef,
	0x55, 0x75, 0xe9, 0xee, 0x82, 0xe9, 0xf0, 0xba, 0x7b, 0x9b, 0xba, 0xb1, 0xc8, 0x8f, 0xac, 0x71,
	0x04, 0x24, 0x7d, 0x9c, 0x33, 0x1f, 0xe8, 0x4a, 0x2c, 0x1f, 0xd6, 0x91, 0x33, 0x9e, 0x81, 0x27,
	0xd1, 0xa6, 0xaa, 0x42, 0x16, 0x80, 0x97, 0x6d, 0xd3, 0x74, 0x91, 0x65, 0xd1, 0x2f, 0xc6, 0x60,
	0xb8, 0x91, 0xe2, 0x49, 0xa4, 0x62, 0x95, 0x2f, 0xa4, 0x14, 0x32, 0x72, 0xda, 0xb6, 0x93, 0x62,
	0xbd, 0xcc, 0x37, 0x77, 0x59, 0xb6, 0x13, 0x72, 0x1e, 0xb9, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0xb6, 0x14, 0x76, 0x89, 0x01, 0x00, 0x00,
}
